# # creando mi propia excepcion
# class ExcepcionCustom(Exception):
#     def __init__(self,error):
#         print(f"Surgio el siguiente error: {error}")

# # Ejecutando mi propia excepcion
# try:
#     raise ExcepcionCustom("Cometiste un error y se lanzo mi excepcion custom")
# except:
#     print("Enserio cometiste ese error?")